#!/bin/bash

set -x


echo "In deploy.sh"


echo "DEBUGGING - in deploy.sh"
echo "GITHUB_ACTION_PATH"
echo "$GITHUB_ACTION_PATH"
echo "ls GITHUB_ACTION_PATH"
ls $GITHUB_ACTION_PATH
exit 0

echo "Running BitOps for env: $BITOPS_ENVIRONMENT"
docker run --rm --name bitops \
-e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
-e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
-e AWS_SESSION_TOKEN="${AWS_SESSION_TOKEN}" \
-e AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" \
-e BITOPS_ENVIRONMENT="${BITOPS_ENVIRONMENT}" \
-e BITOPS_ENVIRONMENT_HELM_SUBDIRECTORY="${BITOPS_ENVIRONMENT_HELM_SUBDIRECTORY}" \
-e SKIP_DEPLOY_TERRAFORM="${SKIP_DEPLOY_TERRAFORM}" \
-e SKIP_DEPLOY_HELM="${SKIP_DEPLOY_HELM}" \
-e TF_STATE_BUCKET="${TF_STATE_BUCKET}" \
-e DEFAULT_FOLDER_NAME="_default" \
-v $(echo $GITHUB_ACTION_PATH)/operations:/opt/bitops_deployment \
bitovi/bitops:2.1.0
