- name: Check Docker exists
  ansible.builtin.command:
    cmd: "docker --version"
  register: docker_check
  ignore_errors: true

- name: Stop and cleanup Docker
  ansible.builtin.command: "docker compose --project-directory {{ app_install_root }}/{{ app_repo_name }} down --remove-orphans --rmi all --volumes"
  register: output
  when: docker_check.rc == 0

- name: Prune Docker system
  command: docker system prune --all --force --volumes
  when: docker_check.rc == 0
