- name: Stop and cleanup Docker
  docker_compose:
    project_src: "{{ app_install_root }}/{{ app_repo_name }}"
    state: absent
    remove_orphans: true
    remove_images: all
    remove_volumes: true
  register: output

- name: Prune Docker system
  command: docker system prune --all --force --volumes