# If applicable mount efs

- name: mount efs
  ansible.builtin.shell: |
    cd {{ app_install_root }}/{{ app_repo_name }}
    mkdir data
    mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_url }}:/{{ resource_identifier }} ./data
  become: true
