# Mount EFS

- name: Install required system packages
  apt: name={{ item }} state=present update_cache=yes
  loop:
    - 'nfs-kernel-server'
    - 'git'
    - 'binutils'

- name: Check if amazon-efs-utils is present
  stat:
    path: /home/ubuntu/efs-utils
  register: check_efs_utils

- name: Cloning amazon-efs-utils from GitHub
  ansible.builtin.git:
    repo: 'https://github.com/aws/efs-utils'
    dest: /home/ubuntu/efs-utils
  become: yes
  when: check_efs_utils.stat.exists

- name: Build amazon-efs-utils
  ansible.builtin.shell: |
    cd /home/ubuntu/efs-utils
    ./build-deb.sh
    apt-get -y install ./build/amazon-efs-utils*deb
  become: yes
  when: check_efs_utils.stat.exists

- name: Creates efs mount directory
  file:
    path: "{{ app_install_root }}/{{ app_repo_name }}/data"
    state: directory

- name: Mount ephemeral SMB volume
  ansible.posix.mount:
    src: {{ efs_url }}:/data
    path: "{{ app_install_root }}/{{ app_repo_name }}/data"
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
    fstype: nfs4
    state: mounted
    boot: false
