# If applicable mount efs

# - name: mount efs
#   ansible.builtin.shell: |
#     mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_url }}:/ {{ lookup('ansible.builtin.env', 'MOUNT_TARGET_PATH', default="./data") }}
#   become: true
#   chdir: "{{ app_install_root }}/{{ app_repo_name }}"

- name: mount efs
  ansible.builtin.shell: |
    ls .
  become: true
  chdir: "{{ app_install_root }}/{{ app_repo_name }}"
