# Mount EFS


- name: Cloning amazon-efs-utils from GitHub
  ansible.builtin.git:
    repo: 'https://github.com/aws/efs-utils'
    dest: /home/ubuntu/efs-utils
  become: yes

- name: Build amazon-efs-utils
  ansible.builtin.shell: |
    cd /home/ubuntu/efs-utils
    ./build-deb.sh
    apt-get -y install ./build/amazon-efs-utils*deb
  become: yes

- name: mount efs
  ansible.builtin.shell: |
    cd {{ app_install_root }}/{{ app_repo_name }}
    mkdir data
    mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_url }}:/ ./data
  become: true
