# Mount EFS

- name: Install required system packages
  apt: 
    name: "{{ item }}" 
    state: present 
    update_cache: yes
    cache_valid_time: 3600 # 1 hour
  loop:
    - 'nfs-kernel-server'
    - 'git'
    - 'binutils'

- name: Check if amazon-efs-utils is present
  stat:
    path: /home/ubuntu/efs-utils
  register: check_efs_utils

- name: Cloning amazon-efs-utils from GitHub
  ansible.builtin.git:
    repo: 'https://github.com/aws/efs-utils'
    dest: /home/ubuntu/efs-utils
    update: false
  become: yes
  when: not check_efs_utils.stat.exists

- name: Build amazon-efs-utils
  ansible.builtin.shell: 
    cmd: |
      ./build-deb.sh
      apt-get -y install ./build/amazon-efs-utils*deb
    chdir: /home/ubuntu/efs-utils
  become: yes
  when: not check_efs_utils.stat.exists

- name: Check if mount directory is present
  stat:
    path: "{{ app_install_root }}/{{ app_repo_name }}/{{ application_mount_target }}/"
  register: check_efs_mount

- name: Creates efs mount directory
  file:
    path: "{{ app_install_root }}/{{ app_repo_name }}/{{ application_mount_target }}"
    state: directory
  when: not check_efs_mount.stat.exists

## Add to env file
- name: Adding `HOST_DIR` to application .env
  ansible.builtin.lineinfile:
    path: "{{ app_install_root }}/{{ app_repo_name }}/.env"
    line: HOST_DIR="{{ app_install_root }}/{{ app_repo_name }}/{{ application_mount_target }}"
- name: Adding `TARGET_DIR` to application .env
  ansible.builtin.lineinfile:
    path: "{{ app_install_root }}/{{ app_repo_name }}/.env"
    line: TARGET_DIR="{{ data_mount_target }}"

- name: Mount efs volume
  ansible.posix.mount:
    src: "{{ efs_url }}:/{{ efs_mount_target }}"
    path: "{{ app_install_root }}/{{ app_repo_name }}/{{ application_mount_target }}"
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=612,retrans=2,noresvport"
    fstype: nfs4
    state: mounted
    boot: false