# UnMount EFS

- name: Check if efs mount directory is present
  stat:
    path: "{{ app_install_root }}/{{ app_repo_name }}/{{ application_mount_target }}/"
  register: check_efs_mount

- name: stat test
  debug:
    msg: "The file or directory exists"
  when: check_efs_mount.stat.exists

- name: Unmount efs volume
  ansible.posix.mount:
    path: "{{ app_install_root }}/{{ app_repo_name }}/{{ application_mount_target }}"
    state: unmounted
  when: check_efs_mount.stat.exists
